"""plan_id nullable en subscriptions

Revision ID: ba49914ca54d
Revises: 0a91ad29eba7
Create Date: 2026-06-15 21:40:53.049543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba49914ca54d'
down_revision: Union[str, Sequence[str], None] = '0a91ad29eba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
